name: Format Code

on: [push]

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    container:
      image: hongzhengli/cs537-formatter:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run formatter
        working-directory: ${{ github.workspace }}/solution
        run: |
          for ext in "*.cpp" "*.c" "*.cc" "*.cxx" "*.h" "*.hpp" "*.hh"; do
            find . -type f -name "$ext" -exec clang-format -i {} +
          done

      - name: Commit and push changes
        working-directory: ${{ github.workspace }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "style: auto-format C/C++ files"
          git push
