name: runtests

on: [push]

jobs:
  runtest:
    runs-on: ubuntu-latest
    container: hongzhengli/cs537:latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Test
        working-directory: ${{github.workspace}}/tests
        run: ./run-tests.sh -v
